//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalDeploymentTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalDeploymentTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling IIS.
        /// </summary>
        internal static string Enabling_IIS {
            get {
                return ResourceManager.GetString("Enabling_IIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS detection failed asking user for instructions..
        /// </summary>
        internal static string IIS_detection_failed_asking_user_for_instructions {
            get {
                return ResourceManager.GetString("IIS_detection_failed_asking_user_for_instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS enabled.
        /// </summary>
        internal static string IIS_Enabled {
            get {
                return ResourceManager.GetString("IIS_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IIS is not installed.
        /// </summary>
        internal static string IIS_is_not_installed {
            get {
                return ResourceManager.GetString("IIS_is_not_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seams like IIS might not be installed on this system.
        ///Can we enable IIS?.
        /// </summary>
        internal static string IIS_is_not_installed_Text {
            get {
                return ResourceManager.GetString("IIS_is_not_installed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tool needs to run as and Administrator please start the application as administrator or contact your administrator to help you..
        /// </summary>
        internal static string Not_an_Administrator_Error_Text {
            get {
                return ResourceManager.GetString("Not_an_Administrator_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not an Administrator user!.
        /// </summary>
        internal static string Not_an_Administrator_Error_Title {
            get {
                return ResourceManager.GetString("Not_an_Administrator_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to deploy.
        /// </summary>
        internal static string Unable_to_deploy {
            get {
                return ResourceManager.GetString("Unable_to_deploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to deploy SafeBank as IIS is required for it to run..
        /// </summary>
        internal static string Unable_to_deploy_SafeBank_as_IIS_is_required_for_it_to_run {
            get {
                return ResourceManager.GetString("Unable_to_deploy_SafeBank_as_IIS_is_required_for_it_to_run", resourceCulture);
            }
        }
    }
}
